---
# handlers file for node_exporter
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes

- name: Start node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: started

# - name: Restart prometheus
#   ansible.builtin.systemd:
#     name: prometheus
#     state: restarted

- name: Reload prometheus
  ansible.builtin.uri:
    url: http://{{ item }}:9090/-/reload
    method: POST
  with_items: "{{ groups['prometheus'] }}"