---
# handlers file for node_exporter
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true

- name: Restart Node Exporter
  ansible.builtin.systemd:
    state: restarted
    name: node_exporter

- name: Reload Prometheus
  ansible.builtin.systemd:
    state: reloaded
    name: prometheus