# Ansible playbook with roles to deploy Prometheus (outside Kubernetes cluster, for monitoring external hosts), to install Node exporter and add static config to the deployed Prometheus configuration with new host, to deploy ElasticSearch + Kibana, to install fluentbit with configured system log collection (from journald) to the installed ElasticSearch.
- name: Provision SSH key
  hosts: 127.0.0.1
  connection: local
  roles:
    - provision_ssh_key

- name: Prometheus
  hosts: prometheus
  remote_user: root
  become: true
  roles:
    - prometheus

- name: Node Exporter
  hosts: node_exporter
  remote_user: root
  become: true
  roles:
    - node_exporter

- name: EFK stack
  hosts: efk
  remote_user: root
  become: true
  roles:
    - efk

#### Cleanup

# - name: Cleanup tmp folder
#   ansible.builtin.command: /bin/rm -rf /tmp/{{ item }}*
#   become: yes
#   become_user: db_owner
#   with_items:
#     - prometheus
#     - node_exporter