---
# handlers file for logging
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable service
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  with_items:
    - "elasticsearch"
    - "kibana"

- name: Restart service
  ansible.builtin.systemd:
    state: restarted
    name: "{{ item }}"
  with_items:
    - "elasticsearch"
    - "kibana"