---
# handlers file for logging

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start Elasticsearch service
  ansible.builtin.systemd:
    name: elasticsearch
    state: started

- name: Enable Elasticsearch service
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: yes

- name: Start Kibana service
  ansible.builtin.systemd:
    name: kibana
    state: started
    
- name: Enable Kibana service
  ansible.builtin.systemd:
    name: kibana
    enabled: yes