---
# handlers file for logging

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start efk services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - elasticsearch
    - kibana

- name: Enable efk services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - elasticsearch
    - kibana