---
# tasks file for node_exporter
- name: Download and Unarchive package
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy node_exporter executable
  ansible.builtin.copy:
    src: /tmp/node_exporter-{{ version }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    owner: root
    group: root
    mode: '0550'

- name: Create directory for OPTIONS file
  ansible.builtin.copy:
    dest: /etc/sysconfig/node_exporter
    content: |
      OPTIONS=''
    remote_src: yes
    owner: root
    group: root
    follow: yes
    mode: '0770'

- name: Add job to prometheus configuration
  lineinfile:
    path: "/etc/prometheus/prometheus.yml"
    line: >2
        - job_name: "node"
          static_configs:
            - targets: ["{{ ansible_host }}:9100"]
    insertbefore: EOF

- name: Validate Prometheus configuration
  ansible.builtin.command: 'promtool check config /etc/prometheus/prometheus.yml'
  register: validation_result

- name: Show validation result
  debug: msg="{{ validation_result.stdout_lines }}"

- name: Allow all access to tcp port 9100
  community.general.ufw:
    rule: allow
    port: '9100'
    proto: tcp

- name: Copy a service file
  ansible.builtin.copy:
    src: ../files/node_exporter.service
    dest: /usr/lib/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0770'
  notify:
    - Reload systemd
    - Start node_exporter
    - Enable node_exporter
    - Reload prometheus