---
# tasks file for node_exporter
- name: Download and Unarchive package
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy node_exporter executable
  ansible.builtin.copy:
    src: /tmp/node_exporter-{{ version }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    owner: root
    group: root
    mode: "0550"

- name: Check if directory for OPTIONS file exists
  stat:
    path: /etc/sysconfig
  register: options_file_folder

- name: "Check OPTION file location folder"
  debug:
    msg: "OPTION file location folder exists"
  when: options_file_folder.stat.exists and options_file_folder.stat.isdir

- name: Create directory for OPTIONS file
  ansible.builtin.copy:
    dest: /etc/sysconfig/node_exporter
    content: |
      OPTIONS=''
    remote_src: yes
    follow: yes
    owner: root
    group: root
    mode: "0550"
    when: options_file_folder.stat.exists === false

- name: Add job to prometheus configuration
  lineinfile:
    path: "/etc/prometheus/prometheus.yml"
    line: >2
        - job_name: "node"
          static_configs:
            - targets: ["{{ ansible_host }}:9100"]
    insertbefore: EOF

- name: Allow all access to tcp port 9100
  community.general.ufw:
    rule: allow
    port: "9100"
    proto: tcp

- name: Copy a service file
  ansible.builtin.copy:
    src: ../files/node_exporter.service
    dest: /usr/lib/systemd/system/node_exporter.service
    follow: yes
    owner: root
    group: root
    mode: "0550"
  notify: 
    - reload_systemd
    - enable_node_exporter
    - restart_node_exporter
    - reload_prometheus
