---
# tasks file for EFK

# Ensure user and group efk:efk exists on target server host

- name: Ensure group "{{ service_group }}" exists
  ansible.builtin.group:
    name: "{{ service_group }}"
    state: present

- name: Ensure user "{{ service_user }}" exists
  ansible.builtin.user:
    name: "{{ service_user }}"
    group: "{{ service_group }}"
    comment: EFK service user
    shell: /bin/bash
    state: present

### ElasticSearch

- name: Download and Unarchive ElasticSearch package
  ansible.builtin.unarchive:
    src: "{{ package_link_elasticsearch }}"
    dest: /tmp
    remote_src: yes

- name: Move downloaded package Elasticsearch to /srv location
  command: mv /tmp/elasticsearch-{{ version_elasticsearch }} {{ path_elasticsearch }}
  args:
    creates: "{{ path_elasticsearch }}"

- name: Copy Elasticsearch service file
  ansible.builtin.copy:
    src: ../files/elasticsearch.service
    dest: /usr/lib/systemd/system/elasticsearch.service
    owner: "{{ service_group }}"
    group: "{{ service_user }}"
    mode: "0770"

### Kibana

- name: Download and Unarchive Kibana package
  ansible.builtin.unarchive:
    src: "{{ package_link_kibana }}"
    dest: /tmp
    remote_src: yes

- name: Move downloaded package Kibana to /srv location
  command: mv /tmp/kibana-{{ version_kibana }} {{ path_kibana }}
  args:
    creates: "{{ path_kibana }}"

- name: Copy Kibana service file
  ansible.builtin.copy:
    src: ../files/kibana.service
    dest: /usr/lib/systemd/system/kibana.service
    owner: "{{ service_group }}"
    group: "{{ service_user }}"
    mode: "0770"

- name: Recursively change ownership of a files
  ansible.builtin.shell: chmod 0770 -R {{ item }}
  with_items:
    - "{{ path_elasticsearch }}"
    - "{{ path_kibana }}"
  become: true

# Create firewall rules
- name: Apply firewall rules
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "{{ port_kibana }}"
    - "{{ port_elasticsearch }}"
  notify: 
    - Reload systemd
    - Enable services
    - Restart services