---
# tasks file for prometheus

- name: Ensure group prometheus exists
  ansible.builtin.group:
    name: prometheus
    state: present

- name: Ensure user prometheus exists
  ansible.builtin.user:
    name: prometheus
    comment: Prometheus service user
    group: prometheus
    shell: /bin/false
    state: present

- name: Download and Unarchive package
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy prometheus executable
  ansible.builtin.copy:
    src: /tmp/prometheus-{{ version }}.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    remote_src: yes
    owner: prometheus
    group: prometheus
    mode: '0770'

- name: Copy promtool executable
  ansible.builtin.copy:
    src: /tmp/prometheus-{{ version }}.linux-amd64/promtool
    dest: /usr/local/bin/promtool
    remote_src: yes
    owner: prometheus
    group: prometheus
    mode: '0770'

- name: Create directory for configuration file
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0770'
    owner: prometheus
    group: prometheus

- name: Copy configuration file
  ansible.builtin.copy:
    src: /tmp/prometheus-{{ version }}.linux-amd64/prometheus.yml
    remote_src: yes
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0770'

- name: Add prometheus self monitoring job 
  ansible.builtin.replace:
    path: /etc/prometheus/prometheus.yml
    regexp: "localhost:9090"
    replace: "{{ ansible_host }}:9090"

- name: Validate configuration
  ansible.builtin.command: 'promtool check config /etc/prometheus/prometheus.yml'
  register: validation_result

- name: Show validation result
  debug: msg="{{ validation_result.stdout_lines }}"

- name: Create a directory for DB
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    mode: '0770'
    owner: prometheus
    group: prometheus

- name: Create a directory to store service options file
  ansible.builtin.file:
    path: /etc/sysconfig
    state: directory
    mode: '0660'
    owner: prometheus
    group: prometheus

- name: Create a service options file
  ansible.builtin.copy:
    dest: /etc/sysconfig/prometheus
    content: |
      OPTIONS='--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/ --web.enable-lifecycle'
    remote_src: yes
    owner: prometheus
    group: prometheus
    mode: '0770'

- name: Allow all access to tcp port 9090
  community.general.ufw:
    rule: allow
    port: '9090'
    proto: tcp

- name: Copy a service file
  ansible.builtin.copy:
    src: ../files/prometheus.service
    dest: /usr/lib/systemd/system/prometheus.service
    follow: yes
    owner: prometheus
    group: prometheus
    mode: '0770'
  notify:
    - Reload systemd
    - Start prometheus
    - Enable prometheus