---
# handlers file for prometheus
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    
- name: Enable prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes